[package]
name = "meta_creator"
version = "0.1.0"
authors = ["miao jing <243127395@qq.com>"]

[dependencies]
rustc-serialize = "0.3.22"
regex = "0.2"
dotenv = "0.8.0"
log = "0.3.6"
glob = "0.2.11"
toml = "0.2"

[dependencies.env_logger]
version = "0.3.5"
default-features = false
features = []